### ISSUE TITLE
json: cannot unmarshal number <float> into Go struct field ResourceSuggestion.requestedMemory of type int

### ISSUE THREAD

**Issue by caiofralmeida** [spotinst/spotinst-sdk-go#100]
**What happened**: When I try to use the ocean right-sizing mutator on some resources I noticed that a cast `json: cannot unmarshal number 3814.697265625 into Go struct field ResourceSuggestion.requestedMemory of type int` error occurs, analyzing the problem a little more, I saw that the SDK only supports the entire type for the `ResourceSuggestion.RequestedMemory` field (https://github.com/spotinst/spotinst-sdk-go/blob/master/service/ocean/providers/aws/right_sizing.go#L21), I made the request directly in the API and found that it is already returning a floating-point value:

```curl ... https://api.spotinst.io/ocean/aws/k8s/cluster/o-xxx/rightSizing/suggestion?accountId=act-xx&namespace=airflow-data-platform

Response:
       ...
        {
          "deploymentName": "",
          "resourceName": "airflow-data-platform-worker",
          "resourceType": "statefulSet",
          "namespace": "airflow-data-platform",
          "suggestedCPU": 8,
          "suggestedMemory": 1115,
          "requestedCPU": 1000,
          "requestedMemory": 3814.697265625
        },
     ...
```
I don't know if it would be right for the API to always return an integer value or the SDK to cast to int at the moment of unmarshall, this ends up strongly impacting the use of the webhook, because if one of the recommendations of the error, impacts all.

**What you expected to happen**: Return the `requestedMemory` as an integer.

**How to reproduce it (as minimally and precisely as possible):** Call the API that returns a floating-point value and unmarshal through the SDK https://github.com/spotinst/spotinst-sdk-go/blob/master/service/ocean/providers/aws/right_sizing.go#L49

**Anything else we need to know:**

**Environment:** Production

- Go (use `go version` or `go env`): 1.14
- SDK (use `cat spotinst/version.go`): .171.0
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): Linux caio-almeida 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by liranp** [comment]
@caiofralmeida, thank you for the detailed description. We'll fix the Ocean Mutator as well.

**Comment by caiofralmeida** [comment]
Thanks very much, @liranp. The Ocean Mutator has been very useful, we are using it in our staging environment. Nowadays, the Mutator doesn't support Statefulsets, Is there any item in the spot.io backlog to support this resource, or I could contribute directly to the project?

**Comment by liranp** [comment]
That's great to hear. Actually, I'm working on a complete re-write of the project. We hope to have it ready (and released) within a few days.

**Comment by caiofralmeida** [comment]
Great @liranp, we are available to use/test/contribute to the new project implementation, thank you very much! Are you creating a new repository or the project will still at https://github.com/spotinst/ocean-right-sizing-mutator?

**Comment by liranp** [comment]
Thanks for suggesting that. We'd love to hear your feedback. It'll be released in a new repository (probably `spotinst/ocean-mutator`), and a notice will be added to the existing one with a reference to the new one. We'll let you know as soon as it's done.

**Comment by caiofralmeida** [comment]
> @caiofralmeida, thank you for the detailed description. We'll fix the Ocean Mutator as well.

Perfect @liranp, could you please let me know when the current ocean mutator is fixed?
