### ISSUE TITLE
Support ocean/aws/k8s/cluster/{clusterIdentifier}/log

### ISSUE THREAD

**Issue by cep21** [spotinst/spotinst-sdk-go#115]
**What would you like to be added?**
Add support for fetching Ocean AWS logs to the SDK

**Why is this needed?**

I would like to import Ocean logs into my monitoring solution.  There do not appear to be any native integration for this (Datadog in my case).  I would like to write my own and the spotinst-sdk-go seems like a good tool to leverage: however it does not currently support fetching logs.  I believe the endpoint I need is https://docs.spot.io/api/#operation/oceanAwsFetchLog.

**Comment by liranp** [comment]
A usage example is available [here](https://github.com/spotinst/spotinst-sdk-go/blob/v1.81.0/examples/service/ocean/providers/aws/logevents/main.go).
