### ISSUE TITLE
Missing attributes for GKE launch spec

### ISSUE THREAD

**Issue by ycabrer** [spotinst/spotinst-sdk-go#126]
**What happened**:
Unable to set 
```
	Tags               []*Tag              `json:"tags,omitempty"`
	IPForwarding       *bool               `json:"ipForwarding,omitempty"`
	RootVolumeSizeInGB *int                `json:"rootVolumeSizeInGb,omitempty"`
	ServiceAccount     *string             `json:"serviceAccount,omitempty"`
```

**What you expected to happen**:
Ability to set the fields.

It looks like there are two separate types for gke launch specifications. 

The ocean one having the full list of options
 https://github.com/spotinst/spotinst-sdk-go/blob/master/service/ocean/providers/gcp/cluster.go#L166

And this one that has the above fields missing is used for creating the launch specifications  https://github.com/spotinst/spotinst-sdk-go/blob/master/service/ocean/providers/gcp/launchspec.go#L15

**How to reproduce it (as minimally and precisely as possible):**

**Anything else we need to know:**

**Environment:**

- Go (use `go version` or `go env`):
- SDK (use `cat spotinst/version.go`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by liranp** [comment]
Release [v1.91.0](https://github.com/spotinst/spotinst-sdk-go/releases/tag/v1.91.0) is available now.
