### ISSUE TITLE
add support for administration of organizations and accounts

### ISSUE THREAD

**Issue by smenton-tunein** [spotinst/spotinst-sdk-go#161]
**What would you like to be added?**

The API docs have endpoints for administration of [organizations](https://docs.spot.io/api/#tag/Organizations) and [accounts](https://docs.spot.io/api/#tag/Accounts). Being able to hit these endpoints to manage those resources could be added to this SDK.

**Why is this needed?**

Administration of users at the organization or account level is useful in onboarding and offboarding staff. If these were added to the SDK it would be easier to automate administration activities. Better still it would enable adding to the [Spotinst Terraform provider](https://github.com/spotinst/terraform-provider-spotinst) so that access can be managed as code.

**Comment by Noham1412** [comment]
Hi @smenton-tunein, thank you for your feedback.
This is something we'll consider adding to the Terraform registry.
We are developing new ‘user management’ capabilities and they are scheduled to be released in the near future.

After that, we'll have new API routes, and we'll evaluate adding them to the TF registry (and as part of that they will be added to GO SDK).

**Comment by anuragsharma-123** [comment]
We have user management supported in Terraform Provider now. Please check the documentation - https://registry.terraform.io/providers/spotinst/spotinst/latest/docs/resources/organization_user

**Comment by anuragsharma-123** [comment]
We have user management supported in terraform provider now. Please check the following link -
