### ISSUE TITLE
Get Security Id by name using spot api

### ISSUE THREAD

**Issue by balu-ce** [spotinst/spotinst-sdk-go#215]
> I am trying to develop a provider for spot instance in crossplane.
> 
> The input is coming security Id name , Is there is an API to get security id by the name.

**Comment by guyalt3** [comment]
Hey, I don't understand exactly what is security id. Do you mean security group id or something different? can you clarify please?

**Comment by anuragsharma-123** [comment]
Hi @balu-ce - Are you still working on this crossplane integration?

**Comment by anuragsharma-123** [comment]
Closed. Seems like a stale issue. Please reopen if you still need us to look into this issue.
