### ISSUE TITLE
rootVolumeSize must not exist simultaneously with [blockDeviceMappings]

### ISSUE THREAD

**Issue by msvechla** [spotinst/spotinst-sdk-go#287]
**What happened**:

Using the [terraform-provider-spotinst](https://github.com/spotinst/terraform-provider-spotinst) we get the following error:

> "rootVolumeSize" must not exist simultaneously with [blockDeviceMappings]

Even though `rootVolumeSize` is set to `null`

**What you expected to happen**: 

We expect not to see the error when `rootVolumeSize` is not specified

**How to reproduce it (as minimally and precisely as possible):**

see the issue here: https://github.com/spotinst/terraform-provider-spotinst/issues/512

**Anything else we need to know:**

It looks like the issue is coming from [here](https://github.com/spotinst/spotinst-sdk-go/blob/8cf35e32fb37046382a46a60e3a5edc6d7cd3637/service/ocean/providers/aws/cluster.go#L1645C1-L1650C2) where `RootVolumeSize` is set as `nullFields`, causing them to be included in the request, when it should actually be omitted according to your API docs:

https://docs.spot.io/api/#tag/Ocean-AWS/operation/OceanAWSClusterUpdate

> `blockDeviceMappings`: Block devices that are exposed to the instance. You can specify virtual devices and EBS volumes.
This parameter and rootVolumeSize cannot be in the specification at the same time.
This parameter can be null. If not null, it must contain at least one block device.

"This parameter and rootVolumeSize cannot be in the specification at the same time." reads for me like we should not include `rootVolumeSize` when it is `null`

**Comment by chandra1-n** [comment]
@msvechla Thanks for bringing up the issue here, as of now it is the behavior of the API where-in we cannot have root_volume_size and bdm updated together, but if you need to remove the root_volume_size and add bdm block then you can achieve through 2 separate updates - 1 removing root_volume_size and the second to add bdm block.
Closing this ticket as it is not terraform provider issue.
