### ISSUE TITLE
Add missing suspend API

### ISSUE THREAD

**Issue by lmineiro** [spotinst/spotinst-sdk-go#36]
The [API to suspend processes (at least AWS provider)](https://api.spotinst.com/spotinst-api/elastigroup/amazon-web-services/suspend-processes/) doesn't seem to be available in the SDK.

**Comment by omerspot** [comment]
Hi @lmineiro! 
Hope you're well
The resource was added, unfortunately the provider docs weren't updated properly.

Here's the relevant usage example:

# Create a suspension for Elastigroup
```
resource "spotinst_elastigroup_aws_suspension" "resource_name" {
  group_id = "sig-12345678"

  suspension {
    name = "OUT_OF_STRATEGY"
  }

  suspension {
    name = "REVERT_PREFERRED"
  }

  suspension  {
    name = "PREVENTIVE_REPLACEMENT"
  }
}
```

## Arguments

* `group_id` - (Required; string) Elastigroup ID to apply the suspensions on.
* `suspension` - (Required; at least one block is required) block of single process to suspend.
    * `name` - (Required; string) The name of process to suspend. 
         * `Valid values`: `"AUTO_HEALING" , "OUT_OF_STRATEGY", "PREVENTIVE_REPLACEMENT", "REVERT_PREFERRED", or "SCHEDULING"`.
