### ISSUE TITLE
Ocean Cluster Cost API support

### ISSUE THREAD

**Issue by hanjunlee** [spotinst/spotinst-sdk-go#92]
**What would you like to be added to?**

Hi, when I've tried to use the [Ocean cluster cost API](https://docs.spot.io/api/#operation/oceanAwsClusterCosts) but I couldn't find it in this package. I'm curious that I've missed something or it's not supported yet? Thank you.

**Why is this needed?**

In the company, I'm working on making a dashboard for the cost of infrastructure which has the cost of Spotinst ocean. So I need the Ocean cost API.

**Comment by liranp** [comment]
It's available [here](https://github.com/spotinst/spotinst-sdk-go/blob/master/service/mcs/mcs.go#L106-L139). Usage example:
```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/spotinst/spotinst-sdk-go/service/mcs"
	"github.com/spotinst/spotinst-sdk-go/spotinst"
	"github.com/spotinst/spotinst-sdk-go/spotinst/session"
	"github.com/spotinst/spotinst-sdk-go/spotinst/util/stringutil"
)

func main() {
	// Create a new session.
	sess := session.New()

	// Create a new instance of the service's client with a Session.
	svc := mcs.New(sess)

	// Create a new context.
	ctx := context.Background()

	// Read cluster costs.
	out, err := svc.GetClusterCosts(ctx, &mcs.ClusterCostInput{
		ClusterID: spotinst.String("o-12345"),
		FromDate:  spotinst.String("yyyy-mm-dd"),
		ToDate:    spotinst.String("yyyy-mm-dd"),
	})
	if err != nil {
		log.Fatalf("spot: failed to read cluster costs: %v", err)
	}

	// Output.
	fmt.Printf("%s\n", stringutil.Stringify(out.ClusterCosts))
}
```

**Comment by hanjunlee** [comment]
Appreciate it!
